# Generated by Django 5.1 on 2024-08-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_equipo_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='daniado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
