# Generated by Django 5.1 on 2024-08-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_arriendo_daniado_alter_arriendo_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='create',
            field=models.DateField(auto_now_add=True),
        ),
    ]
